services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - DB_NAME=livesitter_demo
      - CORS_ORIGINS=* # Be more specific for security
      - FFMPEG_BIN=ffmpeg
    volumes:
      - ./server/streams:/app/streams
    depends_on:
      - mongo

  client:
    build: ./client
    ports:
      - "3000:80" # Map host port 3000 to the container's port 80
    depends_on:
      - server

volumes:
  mongo-data: